$path = "C:\Users\AnzarAli\Desktop\storywebsite2\Content\Story.md"
$fullStory = @()

# Append helper
function Add-Part([string[]]$lines) {
    $global:fullStory += $lines
}

# PROLOGUE
Add-Part @('# The Lantern of Ashara', '', '## Prologue', '', 
'The world had once been held together by stories.', '',
'In the city of Ashara, every wall was a page, every lantern a sentence, and every storyteller a keeper of the fragile light that kept the dark from swallowing the night. When the first silence came, it was not thunderous. It arrived quietly, in a sudden stillness between a mother` lullaby and a boy whispered wish.', '',
'No one knew why the songs stopped.', '',
'Some said it was the work of the Silence, an ancient creature that fed on sound and memory, growing stronger each time a story was forgotten. Others said it was a curse placed upon the city by a jealous god who could not bear the laughter of mortals. Still others believed it was simply the natural way of things—that all sounds, like all lives, must eventually fade. But the old ones, the ones who still remembered the songs of their grandmothers and the tales carved into the bones of the earth, knew better. They knew that silence was not merely the absence of sound. It was a presence—a living, breathing thing that moved through the streets like smoke, coiling around the ankles of those who dared to speak, whispering that their words did not matter.', '',
'And so the people of Ashara, who had once filled the night with music and the air with the fragrance of burning stories, began to forget. Not all at once, but slowly, like water wearing away at stone. First, it was the children who stopped singing in the streets. Then the merchants lost their calls, and the bakers forgot the prayers they once whispered over their ovens. The elders sat in their chairs and stared at the walls, their lips moving as if trying to recall something just beyond reach, but the words would not come.', '',
'The lantern-makers noticed it first. Their lanterns, which had always glowed with a warm and steady light, began to flicker and dim, as if the very flames had lost the will to burn. The glass that once shone with the brilliance of a thousand captured sunsets now looked dull and lifeless, like the eyes of the dead. And in the silence that followed, something stirred—a darkness that had never truly been vanquished, only sleeping, waiting for the moment when the world would forget how to fight it.', '',
'Ashara had been founded in the Age of Voices, when the first wanderers came across the desert carrying nothing but lanterns and the stories they had memorized in their hearts. They had traveled far from the lands of dust and silence, fleeing a great war that had consumed their homeland. When they reached the place where Ashara now stood, they found a grove of ancient trees whose roots drank from an underground river, and they decided to rest there. One evening, as the sun sank behind the western mountains and the sky turned the color of bruised plums, the eldest among them—an old woman named Ashara, for whom the city would be named—stood up and began to speak.', '',
'She told a story about a fisherman who had once lived by a silver sea, and every night he would light a lantern and place it at the edge of the water so that the fish could find their way home. The fish, grateful for the light, would sing to the lantern each evening, and their songs would carry across the water to the shore, where the fisherman` daughter would listen and weave their melodies into blankets of sound. The blankets kept the village warm through the long winters, and the people who lived there never knew hunger or despair, because the songs of the fish reminded them that they were not alone.', '',
'When Ashara finished speaking, the wanderers wept, for they had not heard a story in many days, and the sound of a human voice—warm and alive and full of meaning—was more precious to them than water in the desert. They asked her to tell another, and another, and another. And so she did. Night after night, Ashara sat by the fire and told stories, and the wanderers gathered around her, and the stories became the foundation upon which they built their new home.', '',
'They built their houses from the stories, each wall a sentence, each roof a chorus. They paved their streets with the rhythms of Ashara` voice, and they planted gardens whose flowers bloomed in patterns that mirrored the narrative arcs of her tales. At the center of the city, they raised a great lantern—a lantern that would never go out as long as someone was willing to tell a story beneath it. And that lantern, the Lantern of Ashara, became the heart of the city, the source of its light and its life.', '',
'Generations passed, and the city grew. The wanderers became settlers, and the settlers became citizens, and the citizens became the people of Ashara—a people defined not by their borders or their armies but by their stories. Every child born in the city was given a name drawn from a story, and every death was marked not with a tombstone but with a tale that was added to the ever-growing library of the city` memory. The lantern-makers learned to capture stories in glass, and their lanterns became living archives, each one a vessel for a piece of the city` soul.', '',
'But the people of Ashara were not the only ones who valued stories. Far beneath the city, in the deep places where the underground river ran dark and cold, something else listened. Something that had existed before Ashara was founded, before the first wanderer crossed the desert, before the first story was ever told. It was the Silence—the absence given form, the void that had been displaced by the sound of creation. The Silence did not hate stories. It simply could not bear them, because every story was a reminder of a world that existed before the void, a world full of light and noise and life. And so the Silence waited, patient as stone, feeding on the moments when people forgot to speak, growing stronger with each unspoken word.', '',
'No one knew exactly when the Silence began to stir again. Some said it was when the last of the original wanderers died, taking their firsthand memories of the founding with them. Others said it was when the great library—the Hall of Names—was sealed, its doors locked and its keys lost to time. But whatever the cause, the Silence crept back into the city like a tide, inch by inch, story by story. First, it was the small tales that disappeared—the nursery rhymes, the marketplace chants, the jokes shared between friends. Then the larger stories began to fade, the ones that had been passed down through families for generations. And finally, the Silence reached for the most sacred stories of all—the tales of Ashara` founding, the songs that had built the city` walls—and it took them, too, swallowing them into the void like a creature consuming its prey.', '',
'Now, as Nira would soon discover, the Silence had nearly won. But not quite. Because there was still one lantern that burned, and one girl who could hear its voice.', '')

# CHAPTER ONE
Add-Part @('', '## Chapter One: The Girl Who Listened', '',
'Nira had always listened differently.', '',
'From the moment she could walk, she had pressed her ear to the ground, trying to hear what the earth was saying. She would sit for hours in the garden behind her mother` stall, her knees drawn to her chest, her eyes closed, her breath shallow, as if she were trying to become part of the soil itself. The other children thought she was strange. They called her the Listener and whispered behind her back when they thought she could not hear them, but Nira did not mind. She had learned long ago that the world was full of sounds that most people could not hear—the whisper of roots growing beneath the earth, the murmur of stones remembering the weight of the mountains that had once covered them, the soft sigh of the wind as it moved through the cracks in old walls, carrying with it the echoes of conversations long past.', '',
'In the city of Ashara, where the streets were paved with ancient stone and the buildings rose in tiers like the petals of a great flower, there were sounds everywhere for those who knew how to listen. The market was Nira`s favorite place. Not for the goods it sold—though the spices and silks and polished stones were beautiful in their own way—but for the symphony of life that played there every day. The rhythmic clang of the blacksmith` hammer, the soft thud of the weaver` shuttle, the creak of cart wheels on cobblestones, the laughter of children chasing each other through the narrow alleys—all of it was music to Nira`s ears, a composition that no musician could rival.', '',
'At the age of seven, Nira had tried to explain this to her mother. She had come home from the market one evening, her eyes bright with excitement, and told Yasmin about a melody she had heard in the sound of coins clinking together in a merchant` pouch. "It was like a song, Mother," she had said, holding up a copper coin so her mother could see it. "It went up and down, like the notes on Old Maren` piano."', '',
'Yasmin had smiled and kissed Nira`s forehead, but Nira could see in her mother`s eyes that she did not quite understand. "The coins just make noise, little sparrow," Yasmin had said gently. "It is your imagination that turns them into music."', '',
'But Nira knew it was not imagination. The sounds of Ashara were real music, as real as the birdsong in the morning or the bells that rang at the temple each dawn. She could hear the difference between the sound of a happy cart horse and a tired one, between the laughter that came from genuine joy and the laughter that came from nervousness, between the whisper of silk and the whisper of cotton. To Nira, the city was not merely a place; it was a symphony, and every person and every object and every breeze was an instrument in its endless performance.', '',
'But it was the craftsmen who fascinated her most. She would watch the potters as they shaped clay on their wheels, their hands moving with a grace that seemed almost supernatural, and she would listen to the way they breathed. Each breath was different—a slow, measured inhalation as they centered the clay, a quick exhale as they pulled the walls upward, a long, steady breath as they shaped the rim. Nira had come to understand that the rhythm of a craftsman`s breath was as unique as a fingerprint, a signature that revealed not only their skill but their mood, their health, their very soul.', '',
'Old Tamsin, the potter who worked closest to Yasmin` stall, had noticed Nira watching her one afternoon. She had looked up from her wheel, her hands still and dripping with wet clay, and had studied Nira`s face for a long moment.', '',
'"You listen to us," Tamsin said. It was not a question.', '',
'Nira had nodded.', '',
'"What do you hear?"', '',
'Nira had thought for a moment, searching for the right words. "I hear your breath," she said finally. "It sounds like the tide. Going in and out, in and out. When you`re working, it goes faster. When you`re thinking, it goes slower."', '',
'Tamsin had set down her tools and had looked at Nira with an expression that the girl could not quite read. "And what does the tide tell you?"', '',
'"Whether you`re happy or sad," Nira said. "Or whether you`re angry, but trying not to be."', '',
'Tamsin had smiled then—a rare, thin smile that did not quite reach her eyes. "You are either a very strange child, Nira, or a very special one. Perhaps they are the same thing."', '',
'The clockmaker` tick was her heartbeat.', '',
'Old Maren, the city`s master clockmaker, lived in a small shop on Lantern Street, and Nira visited him every chance she got. His clocks were famous throughout Ashara—not for their accuracy, though they were said to lose no more than a second in a hundred years, but for the sound they made. Each tick was clear and pure, like a drop of water falling into a still pool, and when the hour struck, the chimes that rang out were so beautiful that people would stop in the middle of the street and close their eyes just to listen.', '',
'The shop was small and cluttered, filled with clocks of every size and description. There were grandfather clocks that reached from floor to ceiling, their wooden cases carved with intricate designs of leaves and flowers. There were table clocks no bigger than a fist, their faces decorated with painted scenes of sailing ships and mountain villages. There were wall clocks with brass pendulums that swung back and forth in lazy arcs, and there were novelty clocks shaped like birds and flowers and little houses. And in the center of it all, on a glass-topped table, sat the Master Clock—a magnificent piece of machinery that Maren had spent forty years building. It was said to be the most accurate clock in all of Ashara, perhaps in all the world, and it ticked with a sound so pure and so steady that Nira sometimes thought she could hear the heartbeat of the universe within it.', '',
'Nira would sit in Maren`s shop for hours, surrounded by the ticking of dozens of clocks, each one keeping its own time, and she would listen. She listened to the way the sounds interacted—the way a deep, resonant tone from the grandfather clock in the corner would meet the bright, silvery chime of the small table clock on the shelf, creating a harmony that was greater than the sum of its parts. She listened to the way the sounds changed throughout the day, growing softer in the afternoon heat, sharper in the cool of the evening. And she listened to the way Maren himself seemed to be part of the music, his hands moving in time with the ticking, his breath rising and falling with the chimes.', '',
'"You hear it, do not you?" Maren once said to her, his eyes bright with something that looked like wonder. He was an old man, tall and thin, with a beard that reached down to his chest and hands that were always stained with oil. "The city has a heartbeat, child. Most people are too busy to notice, but you—you listen."', '',
'Nira had nodded, not knowing what to say. She had never thought of it that way, but now that Maren had said it, she could feel the truth of it in her bones. The city was alive, and its heartbeat was sound.', '',
'"What happens when the heartbeat stops?" she had asked once, the question slipping out before she could think better of it.', '',
'Maren had looked at her then with a seriousness she had never seen in his eyes before. "That," he had said slowly, "is something no one should ever have to find out."', '',
'Now, sitting at his workbench and watching his gnarled fingers move among the delicate gears and springs, Nira understood what he had meant. She could feel the heartbeat of the city faltering, the steady rhythm growing uneven and slow. She could hear it in the silence that had fallen over the market, in the absence of the songs that had once filled the air. And she could hear it, faintly, in the lanterns—that whisper of sound that lived beneath the glass, waiting for someone who knew how to listen.', '',
'Her mother, Yasmin, sold spices at the market near the lantern bazaar. Yasmin was a tall, broad-shouldered woman with strong hands and a laugh that could fill a room. She had come to Ashara as a young woman, a refugee from the southern provinces where the wars had made life unbearable. She had arrived with nothing but a sack of seeds and a knowledge of herbs that had been passed down through her family for generations, and she had built a life from those meager possessions. Her stall was one of the most popular in the market, not because her spices were the cheapest or the most exotic, but because she sold them with stories.', '',
'"Every spice has a history," Yasmin would say, holding up a handful of saffron threads that glowed like captured sunlight. "This came from the fields of Kethara, where the farmers sing to their crops. The songs change the flavor, you know. A saffron grown in silence is bitter, but one grown with music is sweet."', '',
'Nira believed her mother, because she could taste the difference. She could taste the sorrow in the black pepper that came from the northern mountains, where the farmers worked in near-silence, their songs long since taken from them by the wars. She could taste the joy in the cinnamon that came from the eastern islands, where the harvest festivals lasted for days and the air was thick with music and laughter.', '',
"Yasmin's stories were more than just entertainment; they were the threads that connected the present to the past. She spoke of the grandmother she had never met, a woman who had been known throughout their village for her ability to heal with herbs and words alike. \"She would sing to the sick,\" Yasmin would say, her voice low and reverent, \"and the sickness would leave them. Not because the song was magic, but because it reminded them that they were loved, and that love was stronger than any disease.\" Yasmin's stall in the market was a small haven, a place where customers came not only to buy but to belong, gathering around her like moths drawn to the warmth of her voice and the fragrant clouds of her spices.", '',
'Now Yasmin sat behind her stall in silence, her lips moving over the names of her spices like prayers that no longer reached heaven. The colors were still there—the deep reds of the paprika, the golden yellows of the turmeric, the rich browns of the cumin—but the fire behind the colors had gone out. Her eyes, once bright with the light of a thousand stories, were now dim and shadowed, and when Nira looked at her, she could see the same fear that lived in every heart in the city. She could see her mother aging before her eyes, each day adding new lines to her face, new weight to her shoulders, as if the silence were pulling her down into the earth.', '',
"Each night, after the market closed and the crowds had gone home, the lantern-makers would hang their glass bulbs along the street, and Nira would sit on the stone steps outside their workshop and trace the ribbons of warm light with her eyes. The lanterns were beautiful—hand-blown glass in every color imaginable, from the deep blue of a midnight sky to the soft gold of a summer dawn. When they were lit, they seemed to contain not just fire but something more, something that Nira could never quite name. A warmth, perhaps, or a presence, as if each lantern held a small piece of someone's soul.", '',
'The lantern makers were a peculiar people, proud and secretive, with hands that were always stained with soot and eyes that seemed to see things the rest of the world could not. They lived in a narrow alley behind the bazaar, in houses that leaned against one another like old friends sharing secrets. Their workshops were filled with strange tools and stranger materials—glass that sang when you touched it, metal that remembered its shape, wax that burned without heat. And in the center of each workshop stood a furnace, its flames fed not with wood or coal but with stories that the lantern-makers had collected over the centuries. They fed the tales into the fire, and the fire turned them into light, and the light was captured in glass, and the glass became the lanterns that lit the city` streets.', '',
'At the head of the lantern-makers stood old Haim, a man so ancient that no one could remember when he had first arrived in Ashara. He was small and thin, with a face like a weathered map and hands that trembled when he worked but steadied when he wrote. He could not speak—not because he was mute, for he had once been a great storyteller, but because the Silence had taken his voice on the first night it fell over the city, and he had not spoken a word since. Instead, he communicated through writing, scratching letters into parchment or dusting them onto stone with a thin stick of charcoal.', '',
'"We were fools," Haim once wrote to Nira, long after the silence had taken his voice but before the lanterns had begun to dim. "We thought the stories in our lanterns would last forever. We thought we were preserving them. But we were only trapping them. A story cannot live in glass. It needs breath. It needs a voice. It needs to be told, again and again, or it dies."', '',
'Nira had not understood him then. She was only twelve years old, and the idea that a story could die seemed impossible, like saying that the sun could stop shining or that the river could stop running. But now, as she stood in the dim light of the bazaar and watched the lanterns flicker like dying stars, she began to understand what Haim had meant. The stories were fading, and no one was doing anything to stop it.', '',
'Old men of Ashara said that light held memory. If you looked long enough, they claimed, you would see the faces of those who had carried the flame before you. Nira had always thought this was just a story, a piece of the city` endless mythology, but the more she watched the lanterns, the more she began to wonder. There were moments, brief and fleeting, when she thought she could see something moving inside the glass—a shadow, a shape, the suggestion of a face—but when she looked directly, it was gone.', '',
'Her friend Kael, a boy two years older than Nira with unruly dark hair and a smile that could charm birds from the sky, had once told her that the faces were just tricks of the light. "It is the fire playing on the glass," he had said, grinning. "Nothing more. You think too much, Nira." But Kael had not been there on the night the silence came. He had been at his family` house on the western side of the city, and when he had returned to the bazaar the next morning, his eyes were wide with terror and his voice was hoarse from screaming words that no one could seem to hear.', '',
'"They`re gone," he had gasped when he finally found Nira. "All of them. The voices in the lanterns. They were there last night—I could hear them, clear as day—and now they`re just... gone."', '',
"Kael was a boy who lived with his mother and younger sister in a cramped apartment above a tannery on the western edge of the city. His father had been a sailor who had disappeared on a voyage to the northern islands when Kael was very young, and his mother worked long hours at the tannery to keep her family fed. Kael had learned to be resourceful and self-reliant from a young age, skills that served him well on the streets of Ashara. He was quick with his hands, quicker with his tongue, and quickest of all with his smile, which could charm his way out of almost any trouble.", '',
'But Kael was also afraid—afraid of the dark, afraid of being alone, afraid of the silence that had swallowed his voice along with everyone else`s. He had been born with a stutter that grew worse when he was nervous, and the silence had turned his nervousness into a constant companion. He could hear Nira when she spoke—he was one of the few people who could—but he could no longer speak back to her, and the frustration of that loss ate at him like a rat gnawing at a rope.', '',
'When the silence came, it stole those faces first.', '',
'The first evening after the song stopped, Nira arrived at the bazaar to find the lanterns still glowing, but their light was thin and brittle, like frost. The perfumers whispered to one another with no sound coming from their lips. Their mouths moved, their expressions changed, but there was nothing—no whisper of breath, no rustle of tongue against teeth. The young boys stopped their games mid-laughter and simply stared. The city had become a place of small movements and air thick with unspoken fear.', '',
'Nira felt a cold hand close around her chest. She knelt beside an old lantern-maker whose hands trembled. He looked up at her and, for a moment, she saw his eyes fill with stars.', '',
'"Listen," he mouthed.', '',
'Nira pressed her ear to the wooden table. At first there was nothing but the faint drone of distant heartbeats. Then, beneath the silence, she heard a pulse—a whisper like a thread pulled through wool. It came from the lantern itself.', '',
'The lantern was speaking.', '')

# CHAPTER TWO
Add-Part @('', '## Chapter Two: The City of Hidden Doors', '',
'Ashara was a city built on layers.', '',
'Under the tiles of the market square, under the foundations of the warehouses, there were rooms and halls that no one visited for generations. The city planners had said the old places were unsafe. The priests said they were forbidden. The children called them the Forgotten Ways.', '',
'Nira had always been curious about forbidden places. When the silence spread and strangers came to the city gate with questions and ancient books, she began to understand that the old stories had been warning them all along.', '',
'The lantern-maker, named Haim, could not speak, but he could still write. He scratched letters into a scrap of parchment with fingers that moved as though haunted.', '',
'"Light remembers," he wrote. "The silence feeds on what is forgotten. There is a door beneath the southern square. Only the one who listens can find it. Take the lantern. Trust the song in your bones."', '',
'Nira`s heart beat harder. Trust, she thought, because that was what listening meant; it meant believing in something invisible.', '',
'She took one of Haim` lanterns. It was heavier than it looked, its glass glowing faintly from within. As she carried it through the streets, she felt the silence press against her ears like heavy velvet. The air smelled of cinnamon and old paper. Children moved in slow arcs, as if the world itself had become syrup.', '',
'Beneath the southern square, in a corner hidden by cracked tiles and ivy, Nira found a seam in the stone. When she placed the lantern against it, the glass flared with a violet light. The wall grew thin and an outline appeared—a doorway that was not really there until she believed it.', '',
'The door opened with a sigh.', '')

# CHAPTER THREE
Add-Part @('', '## Chapter Three: The Forest of Forgotten Songs', '',
'The stair led down into darkness, but the lantern lit the way with a steady pulse. The deeper Nira went, the more she realized that the silence had weight. It leaned against the stone walls like a sleeping creature, and every step she took woke it a little.', '',
'When she reached the bottom, she stepped into a forest of old songs.', '',
'Not a forest of trees, but of voices. They hung in the air like lanterns, threads of light and sound braided together. Some were bright and young, others dim as ashes. They swayed on invisible branches, and each one contained a story that had been forgotten.', '',
'Nira reached out. Her fingers brushed a song about a fisherman who had once sailed beyond the sand-walls. Another about a woman who stitched maps into the hems of her dresses. Each memory tasted like a different spice.', '',
'A whisper drifted to her from the right, softer than breath.', '',
'"You hear us," it said.', '',
'Nira turned. The voice had no mouth, just a glow like a pearl in the dark. It was not a voice she had ever heard before, yet it felt familiar, like the echo of her own heartbeat.', '',
'"Who are you?" she asked.', '',
'"We are what was left when people stopped telling. We are the songs undone. You carry a lantern and the courage to listen. The silence is not only outside; it is inside the city and inside the people. To break it, you must light the stories again."', '',
'"How?" she whispered.', '',
'"Find the first tale," the light replied. "The one that began the city. It waits under the root of the oldest tree in the Hall of Names. But be warned: silence likes to hide in truths. It will ask you for more than answers."', '',
'Nira nodded, though she was not sure if she understood the warning. She followed the thread of voice deeper into the forest. Each step uncovered new songs, and the silence grew thinner.')

# Save Part 1 (Prologue through Chapter Three beginning)
$part1 = $fullStory -join "`r`n"
[System.IO.File]::WriteAllText($path, $part1)
$wc = ($part1 -split '\s+').Count
Write-Host "Part 1 written: $wc words"